//SignUp
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const RESET_SIGNUP_STATE = "RESET_SIGNUP_STATE";

//Confirm SignUp
export const CONFIRM_SIGNUP_SUCCESS = "CONFIRM_SIGNUP_SUCCESS";
export const CONFIRM_SIGNUP_PENDING = "CONFIRM_SIGNUP_PENDING";
export const CONFIRM_SIGNUP_FAIL = "CONFIRM_SIGNUP_FAIL";
export const RESET_CONFIRM_STATE = "RESET_CONFIRM_STATE";

// SignIN
export const SIGNIN_PENDING = "SIGNIN_PENDING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// Get Genders
export const GENDERS_PENDING = "GENDERS_PENDING";
export const GENDERS_SUCCESS = "GENDERS_SUCCESS";
export const GENDERS_FAIL = "GENDERS_FAIL";

// Change Password
export const CHANGE_PASSWORD_PENDING = "CHANGE_PASSWORD_PENDING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

// Get Profile Details
export const GET_PROFILE_DETAILS_PENDING = "GET_PROFILE_DETAILS_PENDING";
export const GET_PROFILE_DETAILS_SUCCESS = "GET_PROFILE_DETAILS_SUCCESS";
export const GET_PROFILE_DETAILS_FAIL = "GET_PROFILE_DETAILS_FAIL";

// Edit Profile Details
export const EDIT_PROFILE_DETAILS_PENDING = "EDIT_PROFILE_DETAILS_PENDING";
export const EDIT_PROFILE_DETAILS_SUCCESS = "EDIT_PROFILE_DETAILS_SUCCESS";
export const EDIT_PROFILE_DETAILS_FAIL = "EDIT_PROFILE_DETAILS_FAIL";

//messages
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
